spring:
  datasource:
    url: jdbc:mysql://47.102.214.252:3306/home_service?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: bisha520
    hikari:
      max-lifetime: 10000
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
